version: '2'

services:

  kafka:
    image: eskabetxe:kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.25.0.5
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: 172.25.0.3:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mynet:
        ipv4_address: 172.25.0.5
    depends_on:
      - zookeeper

  zookeeper:
    image: eskabetxe:zookeeper
    ports:
      - "2181:2181"
    networks:
      mynet:
        ipv4_address: 172.25.0.3

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
          IPRange: 172.25.0.2/24,
          gateway: 172.25.0.1